version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start
    depends_on:
      - backend
    mem_limit: 1g
    stdin_open: true
    tty: true
    restart: unless-stopped

  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
